export enum EnumLevel {
    Intern_0 = 0,
    Intern_1 = 1,
    Intern_2 = 2,
    Intern_3 = 3,
    FresherMinus = 4,
    Fresher = 5,
    FresherPlus = 6,
    JuniorMinus = 7,
    Junior = 8,
    JuniorPlus = 9,
    MiddleMinus = 10,
    Middle = 11,
    MiddlePlus = 12,
    SeniorMinus = 13,
    Senior = 14,
    SeniorPlus = 15,
  }