using System;
using System.Collections.Generic;
using Abp.Configuration;
using Microsoft.Extensions.Configuration;

namespace Ncc.Configuration
{
    public class AppSettingProvider : SettingProvider
    {
        public static IConfiguration Configuration { get; } = new ConfigurationBuilder()
              .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
              .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
              .Build();

        public override IEnumerable<SettingDefinition> GetSettingDefinitions(SettingDefinitionProviderContext context)
        {
            return new[]
            {
                new SettingDefinition(AppSettingNames.UiTheme, "red", scopes: SettingScopes.Application | SettingScopes.Tenant | SettingScopes.User, isVisibleToClients: true),
                new SettingDefinition(AppSettingNames.ClientAppId,"null",scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DaysAbsencePerYear,"0",scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DayWorkingHour, "8", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHNEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHNStartAt, "08:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHNStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHNEndAt, "17:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningDNEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningDNStartAt, "8:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonDNStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonDNEndAt, "17:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHCMEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHCMStartAt, "08:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHCMStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHCMEndAt, "17:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningVinhEndAt, "12:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningVinhStartAt, "08:30", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonVinhStartAt, "13:00", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonVinhEndAt, "17:30", scopes:SettingScopes.Application| SettingScopes.Tenant),

                new SettingDefinition(AppSettingNames.MorningHNWorking, "3.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningDNWorking, "4", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningHCMWorking, "3.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MorningVinhWorking, "3.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHNWorking, "4.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonDNWorking, "4", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonHCMWorking, "4.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AfternoonVinhWorking, "4.5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.Holidays, "", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MinWorkingDay, "7", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MinHalfWorkingDay, "3", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LimitedMinutes, "15", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendEmailToSaoDo, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ProjectTaskId, "20078", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockDayOfUser, "Monday", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockHourOfUser, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockMinuteOfUser, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockDayOfPM, "Tuesday", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockHourOfPM, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockMinuteOfPM, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockDayAfterUnlock, "Thursday", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockHourAfterUnlock, "3", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LockMinuteAfterUnlock, "0", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.LogTimesheetInFuture, "false" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MaxTimeSheetHourPerDay, "16" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DayAllowLogTimesheetInFuture, "3" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AutoSubmitTimesheet, "true" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AutoSubmitAt, "Monday" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AutoSubmitAtHour, "8" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalAtHour, "11" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.DateToLockTimesheetOfLastMonth, "5", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.UserLevelSetting, "" , scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.PercentSalaryProbationary, "85", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuUserNameDevMode, "", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.WFHSetting, "3", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.AllowInternToWorkRemote, "false", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.OpenTalkTaskId, "20078", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendEmailTimesheet, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendEmailRequest, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendKomuSubmitTimesheet, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EnableNofityKomuCheckInOutPunishment, "false", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendKomuRequest, "true", scopes:SettingScopes.Application| SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyAtHour,"14",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyOnDates,"10,13,15",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyReviewDeadline,"15",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyPenaltyFee,"50.000",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TotalTimeAbsenceTime,"2",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.WeeksCanUnlockBefor,"1",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NofityKomuCheckInOutPunishmentAtHour, "14", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NofityKomuCheckInOutPunishmentToChannelId, "", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.PercentOfTrackerOnWorking, "90", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInCheckOutPunishmentSetting, "[{\"id\":0,\"name\":\"Không bị phạt\",\"note\":\"Nhân viên check in và check out đúng\",\"money\":0},{\"id\":1,\"name\":\"Đi muộn\",\"note\":\"Nhân viên đi muộn có check in và không check out(tracker đủ) hoặc có check out\",\"money\":20000},{\"id\":2,\"name\":\"Không CheckIn\",\"note\":\"Nhân viên không check in, không check out(tracker đủ)\",\"money\":30000},{\"id\":3,\"name\":\"Không CheckOut\",\"note\":\"Nhân viên check in đúng giờ và không checkout(tracker không đủ)\",\"money\":30000},{\"id\":4,\"name\":\"Đi muộn và Không CheckOut\",\"note\":\"Nhân viên có check in muộn và không có check out(tracker không đủ)\",\"money\":50000},{\"id\":5,\"name\":\"Không CheckIn và không CheckOut\",\"note\":\"Nhân viên không check in và không check out(tracker không đủ)\",\"money\":100000}]", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyOnDates, "10,11,12,13,14,15", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyDeadline, "15", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimesCanLateAndEarlyInMonth, "4", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimesCanLateAndEarlyInWeek, "2", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.GenerateDataOnDate,"6",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TeamBuildingMoney,"100000",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.VAT,"10",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimeStartChangingCheckinToCheckout,"15:00", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimeStartChangingCheckinToCheckoutEnable,"false", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.TimeStartChangingCheckinToCheckoutCaseOffAfternoon,"11:00", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyAtHour, "11", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyOnDates, "1,2,3,4,5", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyTimePeriodWithPendingRequest, "-30", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffSendUserAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyTimePeriodWithPendingRequest, "-30", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHREnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHRAtHour, "10", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftAtHour, "11", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftTimePeriod, "-7", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.MoneyPMUnlockTimeSheet,"20000",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageToPunishUserEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageToPunishUserAtHour, "11", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHRToChannels, "123456789", scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CreateNewRetroEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CreateNewRetroAtHour,"1", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CreateNewRetroOnDate,"1", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.GenerateRetroResultEnableWorker,"false",scopes:SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.GenerateRetroResultAtHour,"2", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.GenerateRetroResultOnDate,"1", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ResetDataTeamBuildingEnableWorker, "false", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ResetDataTeamBuildingAtHour, "1", scopes: SettingScopes.Application|SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ResetDataTeamBuildingOnDateAndMonth, "1/1", scopes: SettingScopes.Application|SettingScopes.Tenant),

                new SettingDefinition(AppSettingNames.SecretRegisterCode, Configuration["DefaultSettings:SecretRegisterCode"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailSaoDo, Configuration["DefaultSettings:EmailSaoDo"], 
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHR, Configuration["DefaultSettings:EmailHR"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.HRMUri, Configuration["DefaultSettings:HRMUri"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ProjectUri, Configuration["DefaultSettings:ProjectUri"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHRDN, Configuration["DefaultSettings:EmailHRDN"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHRHCM, Configuration["DefaultSettings:EmailHRHCM"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.EmailHRVinh, Configuration["DefaultSettings:EmailHRVinh"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.SecurityCode, Configuration["DefaultSettings:SecurityCode"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalUrl, Configuration["DefaultSettings:CheckInInternalUrl"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalAccount, Configuration["DefaultSettings:CheckInInternalAccount"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.CheckInInternalXSecretKey, Configuration["DefaultSettings:CheckInInternalXSecretKey"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.HRMSecretCode, Configuration["DefaultSettings:HRMSecretCode"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ProjectSecretCode, Configuration["DefaultSettings:ProjectSecretCode"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuUri, Configuration["DefaultSettings:KomuUri"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuSecretCode, Configuration["DefaultSettings:KomuSecretCode"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.KomuChannelIdDevMode, Configuration["DefaultSettings:KomuChannelIdDevMode"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NRITNotifyToChannels, Configuration["DefaultSettings:NRITNotifyToChannels"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.RetroNotifyToChannels, Configuration["DefaultSettings:RetroNotifyToChannels"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveTimesheetNotifyToChannels, Configuration["DefaultSettings:ApproveTimesheetNotifyToChannels"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.ApproveRequestOffNotifyToChannels, Configuration["DefaultSettings:ApproveRequestOffNotifyToChannels"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                
                new SettingDefinition(AppSettingNames.SendMessageRequestPendingTeamBuildingToHREmail, Configuration["DefaultSettings:SendMessageRequestPendingTeamBuildingToHREmail"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftToChannels, Configuration["DefaultSettings:NotifyHRTheEmployeeMayHaveLeftToChannels"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
                new SettingDefinition(AppSettingNames.NotifyHRTheEmployeeMayHaveLeftToHREmail, Configuration["DefaultSettings:NotifyHRTheEmployeeMayHaveLeftToHREmail"],
                scopes: SettingScopes.Application | SettingScopes.Tenant),
            };
        }
    }
}
