using Amazon.Runtime.Internal.Transform;
using System;
using System.Collections.Generic;
using System.Text;
using static Ncc.Entities.Enum.StatusEnum;

namespace Timesheet.Uitls
{
    public class AuditLogUtils
    {
        public static Dictionary<string, string> Dict = new Dictionary<string, string>()
            {
            {"Ncc.Timesheets.Customers.CustomerAppService GetAllPagging", " Admin > Clients" },
            {"Ncc.Users.UserAppService GetAllPagging", " Admin > Users" },
            {"Ncc.Users.UserAppService GetUserNotPagging", " Admin > Users" },
            {"Timesheet.APIs.AuditLogs.AuditLogAppService GetAllPagging", " Admin > AuditLogs" },
            {"Timesheet.APIs.Branchs.BranchAppService GetAllNotPagging", " Admin > Branches" },
            {"Timesheet.APIs.Branchs.BranchAppService GetAllPagging", " Admin > Branches" },
            {"Timesheet.APIs.Capabilities.CapabilityAppService GetAllPaging", " Admin > Capability" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService GetAllPaging", " Admin > Capability Setting" },
            {"Timesheet.APIs.KomuTrackers.KomuTrackerAppService GetAllPagging", "Komu Tracker" },
            {"Timesheet.APIs.NormalWorkingHours.NormalWorkingHourAppService GetAllPagging", " Report > Normal Working" },
            {"Timesheet.APIs.OverTimeHours.OverTimeHourAppService GetAllPagging", " Report > Over time" },
            {"Timesheet.APIs.OverTimeSettings.OverTimeSettingAppService GetAllPagging", " Admin > Overtime settings" },
            {"Timesheet.APIs.Positions.PositionAppService GetAllPagging", " Admin > Position" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetAllPagging", " Retro > Retro result" },
            {"Timesheet.APIs.Retros.RetroAppService GetAllPagging", " Retro" },
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService GetAllPagging", "Time keepings" },
            {"Ncc.MultiTenancy.TenantAppService Create", "MultiTenancy" },
            {"Ncc.Roles.RoleAppService Create", " Admin > Roles" },
            {"Ncc.Users.UserAppService Create", " Admin > Users" },
            {"Timesheet.APIs.Capabilities.CapabilityAppService Create", " Admin > Capability" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService CreateCapabilitySetting", " Admin > Capability setting" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService CreateUser", " Admin > Users" },
            {"Timesheet.APIs.Positions.PositionAppService Create", " Admin > Position" },
            {"Timesheet.APIs.ProjectManagement.ProjectManagementAppService CreateCustomer", " Projects > Create customer" },
            {"Timesheet.APIs.ProjectManagement.ProjectManagementAppService CreateProject", " Projects > Create project" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService Create", " Retro > Retro result" },
            {"Timesheet.APIs.Retros.RetroAppService Create", " Retro > Create" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService Create", " Review interns > Review details > Create" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService CreateInternCapability", " Review interns > Review details > Create intern capability" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService Create", " Review interns > Create" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService CreateInternCapability", " Review interns > CreateInternCapability" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService Create", " My timesheets > Log Timesheet" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService CreateByKomu", " My timesheets > Log Timesheet By Discord" },
            {"Ncc.Roles.RoleAppService Update", " Admin > Roles > Update" },
            {"Ncc.Users.UserAppService Update", " Admin > Users > Update" },
            {"Ncc.Users.UserAppService UpdateRole", " Admin > Users" },
            {"Ncc.Users.UserAppService UpdateYourOwnAvatar", " Admin > Users > Update Avatar" },
            {"Timesheet.APIs.Capabilities.CapabilityAppService Update", " Admin > Capability" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService UpdateCapabilitySetting", " Admin > Capability setting > Update" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetInfoToUpdate", " Admin > Users" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService UpdateAvatarFromHrm", " Admin > Users > Update avatar from HRM" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService UpdateUser", " Admin > Users > Update user from HRM" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService UpdateUserInfo", " Admin > Users > Update user info from HRM" },
            {"Timesheet.APIs.Positions.PositionAppService Update", " Admin > Position > Update" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService Update", " Retro > Retro result > Update" },
            {"Timesheet.APIs.Retros.RetroAppService Update", " Retro > Update" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService Update", " Review interns > Review details > Update" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService UpdateLevelHRMv2ForAll", " Review interns > Update level HRM for all" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService UpdateLevelHRMv2ForOne", " Review interns > Update level HRM for one" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService UpdateStarProject", " Review interns > Update star project" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService Update", " My timesheets > Update timesheet" },
            {"Timesheet.Timesheets.Projects.ProjectAppService UpdateDefaultProjectTask", " Projects > Update default project task" },
            {"Ncc.Roles.RoleAppService GetRoleForEdit", " Admin > Roles" },
            {"Timesheet.APIs.MyWorkingTimes.MyWorkingTimeAppService EditWorkingTime", " My working time > Update working time" },
            {"Abp.AspNetCore.Mvc.Controllers.AbpUserConfigurationController GetAll", " Admin > Users" },
            {"Ncc.MultiTenancy.TenantAppService GetAll", "Multi Tenancy" },
            {"Ncc.Roles.RoleAppService GetAll", " Admin > Roles" },
            {"Ncc.Timesheets.Customers.CustomerAppService GetAll", " Admin > Clients" },
            {"Ncc.Users.UserAppService GetAll", " Admin > Users" },
            {"Ncc.Users.UserAppService GetAllInternship", " Admin > Users" },
            {"Ncc.Users.UserAppService GetAllManager", " Admin > Users" },
            {"Ncc.Users.UserAppService GetAllPM", " Admin > Users" },
            {"Timesheet.APIs.AbsenceTypes.AbsenceTypeAppService GetAll", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.AuditLogs.AuditLogAppService GetAllEmailAddressInAuditLog", " Admin > AuditLogs" },
            {"Timesheet.APIs.Branchs.BranchAppService GetAllBranchFilter", " Admin > Branches" },
            {"Timesheet.APIs.Capabilities.CapabilityAppService GetAll", " Admin > Capability" },
            {"Timesheet.APIs.DayOffs.DayOffAppService GetAll", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.HRM.HRMAppService GetAllOverTime", " Report > Over time" },
            {"Timesheet.APIs.HRM.HRMAppService GetAllProject", " Projects" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetAllBanks", " Admin > Users" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetAllRequestDay", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.Info.InfoAppService GetAllHistory", " My profile" },
            {"Timesheet.APIs.Info.InfoAppService GetAllTimesheetLocked1", " My profile" },
            {"Timesheet.APIs.InternInfo.InternsInfoAppService GetAll", " Review interns" },
            {"Timesheet.APIs.InternInfo.InternsInfoAppService GetAllBasicTraner", " Review interns" },
            {"Timesheet.APIs.InternInfo.InternsInfoAppService GetAllBranch", " Review interns" },
            {"Timesheet.APIs.ManageWorkingTimes.ManageWorkingTimeAppService GetAll", " Manage working time" },
            {"Timesheet.APIs.MyWorkingTimes.MyWorkingTimeAppService GetAllMyHistoryWorkingTime", " My working time" },
            {"Timesheet.APIs.Positions.PositionAppService GetAllPosition", " Admin > Positions" },
            {"Timesheet.APIs.Positions.PositionAppService GetAllPositionDropDownList", " Admin > Positions" },
            {"Timesheet.APIs.Public.PublicAppService GetAllCurrentWorkingTimeAllUserWorking", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetAllProject", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetAllUser", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetAllUserByEmail", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetAllUsers", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService KmGetAllUsers", "PublicAppService" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService GetAllMyRequest", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService GetAllRequest", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService GetAllRequestByUserIdForTeamMember", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService GetAllRequestForUser", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService GetAllRequestOfUserByDate", " Manage request off/remote/onsite" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetAllProject", " Retro > Retro details" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetAllProjectByRetroId", " Retro > Retro details" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetAllUserByRetroId", " Retro > Retro details" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetAllUsers", " Retro > Retro details" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetAllUsersNotInTheRetroResultByRetroId", " Retro > Retro details" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService GetAllDetails", " Review interns > Review details" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService GetAll", " Review interns" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService GetAllTimesheetOfUser", " My timesheets" },
            {"Timesheet.Timesheets.Projects.ProjectAppService GetAll", " Projects" },
            {"Timesheet.Timesheets.Tasks.TaskAppService GetAll", " Admin > Tasks" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService GetAll", " Timesheets monitoring" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService GetAllTimeSheetOrRemote", " Timesheets monitoring" },
            {"Timesheet.Timesheets.TimesheetsSupervisor.TimesheetsSupervisor GetAll", " Timesheets monitoring" },
            {"Ncc.Configuration.ConfigurationAppService Get", " Admin > Configuration" },
            {"Ncc.Configuration.ConfigurationAppService GetGoogleClientAppId", " Admin > Configuration"},
            {"Ncc.Configuration.ConfigurationAppService GetHRMConfig", " Admin > Configuration" },
            {"Ncc.Configuration.ConfigurationAppService GetKomuConfig", " Admin > Configuration" },
            {"Ncc.Configuration.ConfigurationAppService GetNotificationSetting", " Admin > Configuration" },
            {"Ncc.Configuration.ConfigurationAppService GetNRITConfig", " Admin > Configuration" },
            {"Ncc.Configuration.ConfigurationAppService GetProjectConfig", " Admin > Configuration" },
            {"Ncc.Configuration.ConfigurationAppService GetUnlockTimesheetConfig", " Admin > Configuration" },
            {"Ncc.Users.UserAppService Get", " Admin > Users" },
            {"Ncc.Users.UserAppService GetRoles", " Admin > Users" },
            {"Ncc.Users.UserAppService GetUserAvatarById", " Admin > Users" },
            {"Ncc.Users.UserAppService GetUserEmailById", " Admin > Users" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService GetCapabilitiesByUserTypeAndPositionId", " Admin > Capability settings" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService GetRemainCapabilitiesByUserTypeAndPositionId", " Admin > Capability settings" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService GetUserTypeForCapabilitySettings", " Admin > Capability settings" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetChamCongInfo", "HRMv2" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetOTTimesheets", "HRMv2" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetPunishmentPMUnlockTS", "HRMv2" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetPunishtmentCheckin", "HRMv2" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetSettingOffDates", "HRMv2" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService GetUserInfoByEmail", "HRMv2" },
            {"Timesheet.APIs.MyAbsenceDays.WFHSetting.WFHSetting Get", " My timesheets" },
            {"Timesheet.APIs.MyWorkingTimes.MyWorkingTimeAppService GetMyCurrentWorkingTime", " My working time" },
            {"Timesheet.APIs.NormalWorkingHours.NormalWorkingHourAppService GetNormalWorkingHourByUserLogin", " Report > Normal working" },
            {"Timesheet.APIs.ProjectManagement.ProjectManagementAppService GetRetroReviewInternHistories", " Projects" },
            {"Timesheet.APIs.Public.PublicAppService GetEffortMonthlyChartProject", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetMyTimeSheets", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetPMsOfUser", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetRetroReviewInternHistories", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetTimesheetOfUserInProjectNew", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetTimesheetWeeklyChartOfProject", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetTimesheetWeeklyChartOfUserGroupInProject", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetTimesheetWeeklyChartOfUserInProject", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetTimeTrackerToDay", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetUserInProjectFromTimesheet", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetUserTimesheetByEmail", "PublicAppService" },
            {"Timesheet.APIs.Public.PublicAppService GetUserWorkFromHome", "PublicAppService" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetProjectPMRetro", " Retro > Retro result" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetProjectPMRetroResult", " Retro > Retro result" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetRetroUserInfo", " Retro > Retro result" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetRetroUserInfo2", " Retro > Retro result" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService GetUserByProjectId", " Retro > Retro result" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService Get", " Review interns > Review detail" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService GetHistories", " Review interns > Review detail" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService GetInternCapability", " Review interns > Review detail" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService GetLevelSetting", " Review interns > Review detail" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService GetLevelSettingForConfirmSalary", " Review interns > Review detail" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService GetUnReviewIntership", " Review interns > Review detail" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService GetReport", " Review interns" },
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService GetDetailTimekeeping", " My timesheets" },
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService GetMyDetails", " My timesheets" },
            {"Timesheet.APIs.Timesheets.AutoSubmitTimesheetSetting.AutoSubmitTimesheetSetting Get", " My timesheets" },
            {"Timesheet.APIs.Timesheets.EmailSaoDoSetting.EmailSaoDoSetting Get", " My timesheets" },
            {"Timesheet.APIs.Timesheets.GetDataFromFaceIDSetting.GetDataFromFaceIDSetting Get", " My timesheets" },
            {"Timesheet.APIs.Timesheets.LevelSettings.LevelSettingAppService Get", " My timesheets" },
            {"Timesheet.APIs.Timesheets.LogTimesheetInFutureSetting.LogTimesheetInFutureSetting Get", " My timesheets" },
            {"Timesheet.APIs.Timesheets.Projects.SpecialProjectTaskSetting.SpecialProjectTaskSetting Get", " Projects" },
            {"Timesheet.APIs.Timesheets.SendKomuPunishedUserCheckInOutSetting.SendKomuPunishedUserCheckInSettingAppService GetPunishedCheckInConfig", " Report > Komu tracker > Get punish" },
            {"Timesheet.APIs.Timesheets.SercurityCodeSetting.SercurityCodeSetting Get", " Admin > Configurations" },
            {"Timesheet.Timesheets.AutoLockTimesheetSetting.AutoLockTimesheetSetting Get", " My timesheets" },
            {"Timesheet.Timesheets.EmailSettings.EmailSettingAppService Get", " Admin > Users" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService Get", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService GetTimesheetReportHours", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService GetTimesheetStatisticClients", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService GetTimesheetStatisticMembers", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService GetTimesheetStatisticProjects", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService GetTimesheetStatisticTasks", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.TimeSheetProjectAppService GetTimeSheetStatisticTasks", " My timesheets" },
            {"Timesheet.Timesheets.MyTimesheets.TimeSheetProjectAppService GetTimeSheetStatisticTeams", " My timesheets" },
            {"Timesheet.Timesheets.Projects.ProjectAppService Get", " Projects" },
            {"Timesheet.Timesheets.Projects.ProjectAppService GetFilter", " Projects" },
            {"Timesheet.Timesheets.Projects.ProjectAppService GetProjectPM", " Projects" },
            {"Timesheet.Timesheets.Projects.ProjectAppService GetProjectsIncludingTasks", " Projects" },
            {"Timesheet.Timesheets.Projects.ProjectAppService GetProjectUser", " Projects" },
            {"Timesheet.Timesheets.Projects.ProjectAppService GetProjectWorkingTimePM", " Projects"},
            {"Timesheet.Timesheets.Projects.ProjectAppService GetQuantityProject", " Projects" },
            {"Timesheet.Timesheets.SingleSignOnSetting.SingleSignOnConfigurationAppService Get", " Admin > Configuration" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService GetQuantiyTimesheetStatus", " My timesheets" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService GetTimesheetWarning", " My timesheets" },
            {"Timesheet.Timesheets.TimesheetsSupervisor.TimesheetsSupervisor GetQuantityTimesheetSupervisorStatus", " Manage timesheets" },
            {"Ncc.Controllers.TokenAuthController GoogleAuthenticate", " Login" },
            {"Ncc.Configuration.ConfigurationAppService SetHRMConfig", " Admin > Configurations > SetHRMConfig" },
            {"Ncc.Configuration.ConfigurationAppService SetProjectConfig", " Admin > Configurations > SetProjectConfig" },
            {"Ncc.Controllers.TokenAuthController Authenticate", " Login" },
            {"Ncc.Configuration.ConfigurationAppService SetNRITConfig", " Admin > Configurations >  SetNRITConfig" },
            {"Timesheet.Timesheets.EmailSettings.EmailSettingAppService Change", " Admin > Users > Change" },
            {"Timesheet.APIs.Timesheets.SercurityCodeSetting.SercurityCodeSetting Change", " Admin > Configurations > Udpate security code" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService CancelRequest", "My request off/remote/onsite > Cancel request" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService SubmitToPendingNew", "My request off/remote/onsite > Send request" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService RejectRequest", "Manage request off/remote/onsite > Reject request" },
            {"Timesheet.APIs.RequestDays.RequestDayAppService ApproveRequest", "Manage request off/remote/onsite > Approved request" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService ApproveTimesheets", "Timesheet > Approved timesheet" },
            {"Timesheet.APIs.ManageWorkingTimes.ManageWorkingTimeAppService ApproveWorkingTime", "Manage working time > Approve working time" },
            {"Ncc.Users.UserAppService ActiveUser", "User > Active User" },
            {"Ncc.Users.UserAppService DeactiveUser", "User > Deactive User" },
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService AddTimekeepingByDay", "Timekeeping > Add timekeeping" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService Approve", "ReviewDetails > Approve" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService ApproveAll", "ReviewDetails > Approve all"},
            {"Timesheet.Timesheets.Tasks.TaskAppService Archive", "Timesheets > Archive" },
            {"Timesheet.APIs.CapabilitySettings.CapabilitySettingAppService CapabilitySettingClone", "Capability settings > Setting clone" },
            {"Ncc.Users.UserAppService ChangeLanguage", "User > Change language" },
            {"Timesheet.APIs.Timesheets.SendKomuPunishedUserCheckInOutSetting.SendKomuPunishedUserCheckInSettingAppService ChangePunishedCheckInConfig", "Change punished checkin config"},
            {"Ncc.Roles.RoleAppService ChangeRolePermission", "Roles > Change role permission" },
            {"Timesheet.APIs.Retros.RetroAppService ChangeStatus", "Retro > Change status"},
            {"Ncc.Users.UserAppService ChangeUserRole", "Users > Change user role"},
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService ConfirmApproveSalary", "Review details > Confirm approved salary" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService ConfirmImportRetro", "RetroDetails > Confirm import retro" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService ConfirmPayslipMail", "HRM > Confirm payslip mail" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService ConfirmUserMaternityLeave", "HRM > Confirm user maternity leave" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService ConfirmUserBackToPause", "HRM > Confirm user to pause" },
            {"Timesheet.APIs.HRMv2.HRMv2AppService ConfirmUserBackToQuit", "HRM > Confirm user back to quit" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService DeActive", "ReviewInterns > DeActive" },
            {"Timesheet.APIs.Positions.PositionAppService Delete", "Positions > Delete" },
            {"Timesheet.APIs.MyWorkingTimes.MyWorkingTimeAppService DeleteWorkingTime", "My woking times > Delete working time"},
            {"Timesheet.APIs.NormalWorkingHours.NormalWorkingHourAppService ExportNormalWorking", "Normal working hours > Export normal working"},
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService ExportReportIntern" , "Review interns > Export reqort intern" },
            {"Timesheet.APIs.RetroDetails.RetroResultAppService ExportRetroResult", "Retro details > Export retro result" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService LockTimesheet" , "Timesheets > Lock timesheet"},
            {"Timesheet.APIs.RetroDetails.RetroResultAppService ImportRetroUserFromFile", "Retro details > Import retro user from file" },
            {"Ncc.Users.UserAppService ImportWorkingTimeFromFile" , "Users > Import working time from file" },
            {"Timesheet.Timesheets.Projects.ProjectAppService Inactive", "Timesheets > Projects > Inactive" },
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService NoticePunishCheckInCheckOut", "Timekeepings > Notice punish check in check out" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService PMReview", "Review details > PM review" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService PMReviewInternCapability", "Review đetails > PM review intern capability"},
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService Reject", "Review details > Reject" },
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService RejectSentMail", "ReviewDetails > Reject sent mail" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService RejectTimesheets", "Timesheet > Reject timesheets" },
            {"Timesheet.APIs.ManageWorkingTimes.ManageWorkingTimeAppService RejectWorkingTime", "Manage working times > Reject working time" },
            {"Ncc.Users.UserAppService ResetPassword", "Users > Reset password"},
            {"Ncc.Timesheets.Customers.CustomerAppService Save", "Customer > Update" },
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService SaveAndReset", "My timesheets > Save and reset"},
            {"Timesheet.APIs.ReviewDetails.ReviewDetailAppService SendEmail", "Review details > Send mail" },
            {"Timesheet.APIs.ReviewInterns.ReviewInternAppService SendEmailsIntern", "Review interns > Send mail to interns"},
            {"Ncc.Configuration.ConfigurationAppService SetNotificationSetting", "Admin Configuration > Set notification setting"},
            {"Ncc.Configuration.ConfigurationAppService SetUnlockTimesheetConfig", "Admin Configuration > Set unlock timesheet config"},
            {"Timesheet.APIs.MyWorkingTimes.MyWorkingTimeAppService SubmitNewWorkingTime" , "MyWorkingTimes > Submit new working time "},
            {"Timesheet.APIs.RequestDays.RequestDayAppService SubmitToPending", "My request off/remote/onsite > Send request" },
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService TraLoiKhieuLai", "Timekeepings > Trả lời khiếu nại" },
            {"Timesheet.Timesheets.Timesheets.TimesheetAppService UnlockTimesheet", "Timesheet > Unlock timesheet"},
            {"Timesheet.APIs.Info.InfoAppService UnlockToApproveTimesheet", "Unlock to approve timesheet"},
            {"Timesheet.APIs.Info.InfoAppService UnlockToLogTimesheet", "Unlock to log to timesheet"},
            {"Timesheet.APIs.Timekeepings.TimekeepingAppService UserKhieuLai", "Timekeeping > User complaint"},
            {"Timesheet.Timesheets.MyTimesheets.MyTimesheetsAppService WarningMyTimesheet", "My timesheet > Warning my timesheet"},
            {"Timesheet.APIs.ProjectManagement.ProjectManagementAppService UserJoinProject", "ProjectManagement > User join project"}
            };
        public static string GetNote(string serviceName, string methodName)
        {
            if (!Dict.ContainsKey(serviceName + " " + methodName)) return "";
            return Dict[serviceName + " " + methodName];
        }
    }
}
